---
title: "Price_Paths"
author: Xiaoxiang Shan
class: Simulation Application
---
```{r}
MYUNIFORM <- function(inputvar)
{
  idum <- inputvar[1]
  numran <- inputvar[2]
  IM1 <- 2147483563
  IM2 <- 2147483399
  IMM1 <- IM1-1
  IA1 <- 40014
  IA2 <- 40692
  IQ1 <- 53668 
  IQ2 <- 52774
  IR1 <- 12211
  IR2 <- 3791
  NTAB <- 32
  NDIV <- as.integer(1+IMM1/NTAB)
  AM=1.0/IM1
  EPS=1.2e-7
  RNMX=1.-EPS
  iv=rep(0,NTAB)
  idum2 <- 123456789
  iy <- 0
  ranx <- rep(0,numran)
  icount <- 1
  for (icount in 1:numran)
  {
    if (idum<=0)
    {
      idum<-max(-idum,1)
      idum2 <- idum
      j<-NTAB+8
      while (j>0)
      {
        k <- as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum<0){idum <- idum+IM1}
        if(j<= NTAB){iv[j] <- idum}
        j <- j-1
      }
      iy <- iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if (idum<0) {idum <- idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2
    if (idum2<0) {idum2 <- idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if (iy<1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    ranx[icount]<-ran2
    icount<-icount+1
  }
  
return(ranx)
}
```
# inverse normal generator
# input is vector of uniform random numbers
```{r}
MYNORM <- function(ran_c)
{
  a0 <- 2.50662823884
  a1 <- -18.61500062529
  a2 <- 41.39119773534
  a3 <- -25.44106049637

  b0 <- -8.47351093090
  b1 <- 23.08336743743
  b2 <- -21.06224101826
  b3 <- 3.13082909833
  
  c0 <- 0.3374754822726147
  c1 <- 0.9761690190917186
  c2 <- 0.1607979714918209
  c3 <- 0.0276438810333863
  c4 <- 0.0038405729373609
  c5 <- 0.0003951896511919
  c6 <- 0.0000321767881768
  c7 <- 0.0000002888167364
  c8 <- 0.0000003960315187
  
  jcount <- 1
  numran <- inputvar[2]
  ran_norm_c <- rep(0,numran)
  while(jcount <= numran)
  {
    u <- ran_c[jcount]
    y <- u-0.5
    if(abs(y)<0.42)
    {
      r <- y*y
      x <- y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else
    {
      r <- u
      if(y>0){r <- 1-u}
      r <- log(-log(r))
      x <- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x <- -x}
    }
    ran_norm_c[jcount] <- x
    jcount <- jcount+1
  } 
  return(ran_norm_c)
}
```
# call uniformrandome number generator (input = seed)
# call normal random number generator (input: uniform random number vector)
```{r}
seed <- -0
numran <-  1000000
inputvar <-  c(seed,numran)
rand_uniform_c <-  MYUNIFORM(inputvar)
rand_uniform_c[1:10]

rand_norm_c = MYNORM(rand_uniform_c)
```
# Price Paths and Average (1,000 paths)
```{r}
S0 <- 100
rf <- 0.03
Volatility <- 0.25
T <- 1/12
numpath <- 1000
Strike <- S0
ST_One <- matrix(rep(0),numpath)
ST_One_Rets <- matrix(rep(0),numpath)
ST_Vals <- matrix(rep(0),nrow=12,ncol=numpath)
SA_Vals <- matrix(rep(0),nrow=12,ncol=numpath)
ST_Rets <- rep(0,numpath)
SA_Rets <- rep(0,numpath)
ST_Vals_avg <- rep(0,numpath)
BS_One_Val <- matrix(rep(0),numpath)
BS_12_Val <- matrix(rep(0),numpath)
BS_max_Val <- matrix(rep(0),numpath)
BS_min_Val <- matrix(rep(0),numpath)
jcount <- 1
lcount <- 1

while(jcount<=numpath)
{
  St <- S0
  SA <- S0
  ST_avg <- 0
  for (kcount in 1:12)
  {
    if(kcount ==1)
    {
      ST_One[jcount] <- S0*(exp((rf-0.5*(Volatility^2))*1+Volatility*sqrt(1)*rand_norm_c[lcount]))
      BS_One_Val[jcount] <- max((ST_One[jcount]-Strike),0)
    }
    St <-St*(exp((rf-0.5*(Volatility^2))*T+Volatility*sqrt(T)*rand_norm_c[lcount]))
    ST_Vals[kcount,jcount] <- St
    ST_avg <- ST_avg+St
    lcount <- lcount+1
  }
  ST_One_Rets[jcount] <- log(ST_One[jcount]/S0)
  ST_Rets[jcount] <- log(ST_Vals[12,jcount]/S0)
  ST_avg <- (ST_avg)/12
  ST_Vals_avg[jcount] <- ST_avg
  BS_12_Val[jcount] <- max((ST_Vals[12,jcount]-Strike),0)
  BS_max_Val[jcount] <- exp(-rf*T*12)*max(max(ST_Vals[1:12,jcount]-Strike),0)
  BS_min_Val[jcount] <- exp(-rf*T*12)*max(ST_Vals[12,jcount]-min(ST_Vals[1:12,jcount]),0)
  jcount = jcount+1
}
  
# below is the returns when modeling S(T) without time discretization, curve is an overlay ofl normal density function
  
  hist(ST_One_Rets,breaks=20,freq=F)
  curve(dnorm(x,mean=0,sd=0.25),from=-4, to =4,add=TRUE, lwd=2)
  hist(BS_One_Val)
  
  
  # Below is the returns when modeling S(T) with time discretization, log-normal case curve is an overlay of normal density function
  hist(ST_Rets, breaks=20, freq=F)
  curve(dnorm(x,mean=0,sd=0.25),from=-4,to=4, add = TRUE,lwd=2)
  
  sprintf("Option value without time discretion: %s",mean(BS_One_Val[1:numpath]))
  sprintf("Max lookback Option: %s",mean(BS_max_Val[1:numpath]))
  CI_max_low = mean(BS_max_Val[1:numpath])+qnorm(0.05)*sd(BS_max_Val[1:numpath])
  CI_max_high = mean(BS_max_Val[1:numpath])-qnorm(0.05)*sd(BS_max_Val[1:numpath])
  sprintf("Max Option Confidence Interval: [%s, %s]", CI_max_low,CI_max_high)
  sprintf("Min lookback Option: %s",mean(BS_min_Val[1:numpath]))
  CI_min_low = mean(BS_min_Val[1:numpath])+qnorm(0.05)*sd(BS_min_Val[1:numpath])
  CI_min_high = mean(BS_min_Val[1:numpath])-qnorm(0.05)*sd(BS_min_Val[1:numpath])  
  sprintf("Min Option Confidence Interval: [%s, %s]", CI_min_low,CI_min_high)
  
```
# Price Paths and Average (10,0000 paths)
```{r}
S0 <- 100
rf <- 0.03
Volatility <- 0.25
T <- 1/12
numpath <- 10000
Strike <- S0
ST_One <- matrix(rep(0),numpath)
ST_One_Rets <- matrix(rep(0),numpath)
ST_Vals <- matrix(rep(0),nrow=12,ncol=numpath)
SA_Vals <- matrix(rep(0),nrow=12,ncol=numpath)
ST_Rets <- rep(0,numpath)
SA_Rets <- rep(0,numpath)
ST_Vals_avg <- rep(0,numpath)
BS_One_Val <- matrix(rep(0),numpath)
BS_12_Val <- matrix(rep(0),numpath)
BS_max_Val <- matrix(rep(0),numpath)
BS_min_Val <- matrix(rep(0),numpath)
jcount <- 1
lcount <- 1

while(jcount<=numpath)
{
  St <- S0
  SA <- S0
  ST_avg <- 0
  for (kcount in 1:12)
  {
    if(kcount ==1)
    {
      ST_One[jcount] <- S0*(exp((rf-0.5*(Volatility^2))*1+Volatility*sqrt(1)*rand_norm_c[lcount]))
      BS_One_Val[jcount] <- max((ST_One[jcount]-Strike),0)
    }
    St <-St*(exp((rf-0.5*(Volatility^2))*T+Volatility*sqrt(T)*rand_norm_c[lcount]))
    ST_Vals[kcount,jcount] <- St
    ST_avg <- ST_avg+St
    lcount <- lcount+1
  }
  ST_One_Rets[jcount] <- log(ST_One[jcount]/S0)
  ST_Rets[jcount] <- log(ST_Vals[12,jcount]/S0)
  ST_avg <- (ST_avg)/12
  ST_Vals_avg[jcount] <- ST_avg
  BS_12_Val[jcount] <- max((ST_Vals[12,jcount]-Strike),0)
  BS_max_Val[jcount] <- exp(-rf*T*12)*max(max(ST_Vals[1:12,jcount]-Strike),0)
  BS_min_Val[jcount] <- exp(-rf*T*12)*max(ST_Vals[12,jcount]-min(ST_Vals[1:12,jcount]),0)
  jcount = jcount+1
}
  
# below is the returns when modeling S(T) without time discretization, curve is an overlay ofl normal density function
  
  hist(ST_One_Rets,breaks=20,freq=F)
  curve(dnorm(x,mean=0,sd=0.25),from=-4, to =4,add=TRUE, lwd=2)
  hist(BS_One_Val)
  
  
  # Below is the returns when modeling S(T) with time discretization, log-normal case curve is an overlay of normal density function
  hist(ST_Rets, breaks=20, freq=F)
  curve(dnorm(x,mean=0,sd=0.25),from=-4,to=4, add = TRUE,lwd=2)
  
  sprintf("Option value without time discretion: %s",mean(BS_One_Val[1:numpath]))
  sprintf("Max lookback Option: %s",mean(BS_max_Val[1:numpath]))
  CI_max_low = mean(BS_max_Val[1:numpath])+qnorm(0.05)*sd(BS_max_Val[1:numpath])
  CI_max_high = mean(BS_max_Val[1:numpath])-qnorm(0.05)*sd(BS_max_Val[1:numpath])
  sprintf("Max Option Confidence Interval: [%s, %s]", CI_max_low,CI_max_high)
  sprintf("Min lookback Option: %s",mean(BS_min_Val[1:numpath]))
  CI_min_low = mean(BS_min_Val[1:numpath])+qnorm(0.05)*sd(BS_min_Val[1:numpath])
  CI_min_high = mean(BS_min_Val[1:numpath])-qnorm(0.05)*sd(BS_min_Val[1:numpath]) 
  sprintf("Min Option Confidence Interval: [%s, %s]", CI_min_low,CI_min_high)
  
```
